### ISSUE TITLE
Eval site is still broken

### ISSUE THREAD

**Issue by jeremylaier** [scala-exercises/exercises-cats#134]
Are we able to stage a release? https://www.scala-exercises.org/cats/Eval is still broken and cannot be completed. I submitted (and merged) a PR ( #127 ) about a month ago fixing this issue. We need to release a new version with that fix for the site to update I believe

**Comment by juanpedromoreno** [comment]
Thanks for the reminder @jeremylaier , I'll try to do a new deployment today.

**Comment by jeremylaier** [comment]
Thanks, I really want the 12/12 completion :)

**Comment by juanpedromoreno** [comment]
I've been facing [this weird issue](https://github.com/scala-exercises/exercises-cats/runs/967337549?check_suite_focus=true#step:9:327) which is preventing the new deployment :(

I'll keep trying this week

**Comment by jeremylaier** [comment]
Have you released since updating scala versions? Seems the error could be due to using scala 2.12 and 2.13 https://github.com/scala-exercises/sbt-exercise/blob/master/build.sbt#L3
