### ISSUE TITLE
Show better errors, i.e. line numbers

### ISSUE THREAD

**Issue by hejfelix** [scala-exercises/exercises-cats#27]
It would be a _huge_ improvement if the quizzes would give a position (which line was the failed assertion?). I appreciate, that in this way, we are not getting the answers, but maybe as an easy fix, split each line into it's own box to make locating your mistakes much easier.

**Comment by raulraja** [comment]
@andyscott Do you think we can point out the line where the failed assertions happen ^^^

**Comment by raulraja** [comment]
This issue was moved to scala-exercises/scala-exercises#509
