### ISSUE TITLE
First example in Semigroups does not work on current web-site

### ISSUE THREAD

**Issue by teliatko** [scala-exercises/exercises-cats#64]
Hi all I've found inconsistency in first exercise of exercises-cats. More precisely code on server is using modified example where https://github.com/scala-exercises/exercises-cats/blob/master/src/main/scala/catslib/Semigroup.scala#L48 was split to two. But text on the website is still using the old one. What is the update process of the web-site? Should I file an issue?
To put it simply, first exercise in https://www.scala-exercises.org/cats/semigroup does not work.

Steps to reproduce:

**Comment by FRosner** [comment]
Duplicates #65
