### ISSUE TITLE
First example in Semigroups does not work on current web-site

### ISSUE THREAD

**Issue by teliatko** [scala-exercises/exercises-cats#65]
Hi all I've found inconsistency in first exercise of exercises-cats. More precisely code on server is using modified example where https://github.com/scala-exercises/exercises-cats/blob/master/src/main/scala/catslib/Semigroup.scala#L48 was split to two. But text on the website is still using the old one. What is the update process of the web-site? Should I file an issue?
To put it simply, first exercise in https://www.scala-exercises.org/cats/semigroup does not work.

Steps to reproduce:

Go to web site https://www.scala-exercises.org/cats/semigroup and fill the first example, you will get the error. By me it looks like:

```
import cats.implicits._

Semigroup[Int].combine(1, 2) should be( 3 )
Semigroup[List[Int]].combine(List(1, 2, 3), List(4, 5, 6)) should be( List(1,2,3,4,5,6) )
Semigroup[Option[Int]].combine(Option(1), Option(2)) should be( Some(3) )
Semigroup[Option[Int]].combine(Option(1), None) should be( Some(1) )
Semigroup[Int ⇒ Int]
  .combine({ (x: Int) ⇒
    x + 1
  }, { (x: Int) ⇒
    x * 10
  })
  .apply(6) should be( 67 )
```

Click run, you will get:

`Evaluation failed : Compilation Error ; ERROR -> too many arguments for method semigroupCombine: (res0: Int, res1:
`
IMHO the site is just obsolete, that all.

**Comment by FRosner** [comment]
Hi @anamariamv! Is that related to the last time when you deployed a new version and an outdated exercise was not removed from the page?

**Comment by anamariamv** [comment]
@FRosner I'll take a look.

**Comment by anamariamv** [comment]
@FRosner and @teliatko  We have redeploy the main site and fixed this issue. 

<img width="864" alt="screen shot 2018-01-07 at 22 49 32" src="https://user-images.githubusercontent.com/2183589/34654526-324e3a06-f3fd-11e7-8dcf-027ed714a0c9.png">

**Comment by teliatko** [comment]
I'm still getting the error

![image](https://user-images.githubusercontent.com/242544/34666171-4a2c45d0-f463-11e7-8d60-783d4426950e.png)

What should I do, am I doing something wrong?

**Comment by teliatko** [comment]
Detail of POST request

![image](https://user-images.githubusercontent.com/242544/34668203-98a22c4e-f46c-11e7-8a94-b1d4579f7e18.png)
